### ISSUE TITLE
看下这个报错

### ISSUE THREAD

**Issue by WhiteCjy** [libuke/aliyundrive-checkin#16]
Run python3 ./main.py --token_string "***"
Traceback (most recent call last):
  File "/home/runner/work/aliyundrive-checkin/aliyundrive-checkin/./main.py", line 52, in <module>
    main()
  File "/home/runner/work/aliyundrive-checkin/aliyundrive-checkin/./main.py", line 35, in main
    result = ali.aliyundrive_check_in(token)
  File "/home/runner/work/aliyundrive-checkin/aliyundrive-checkin/aliyundrive.py", line 28, in aliyundrive_check_in
    flag, user_name, access_token, refresh_token, message = self._get_access_token(token)
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by Ssiswent** [comment]
+1，我也一样
![image](https://github.com/libuke/aliyundrive-checkin/assets/37449310/03535357-665d-4c06-8455-87fba7925714)
![image](https://github.com/libuke/aliyundrive-checkin/assets/37449310/1344f3df-e6fc-452a-897f-24eac16744ea)

**Comment by libuke** [comment]
代码报错已修复，阿里云盘Token过期了，重新获取下就好了。

**Comment by Ssiswent** [comment]
> 代码报错已修复，阿里云盘Token过期了，重新获取下就好了。

可是这是我刚刚扫码获取的Refresh Token...

**Comment by Ssiswent** [comment]
刚刚试了下运行Action，是一样的报错

**Comment by libuke** [comment]
> 刚刚试了下运行Action，是一样的报错

重新选择Action 点击Run workflow
不能在失败的任务中点重新运行
